version: '3.8'

services:
  app:
    build: .
    container_name: midimealy-app
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

