/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficesIndexRouteImport } from './routes/offices/index'
import { Route as RestaurantRestaurantIdRouteImport } from './routes/restaurant/$restaurantId'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as OfficesOfficeIdRouteImport } from './routes/offices/$officeId'
import { Route as OfficesOfficeIdSearchRouteImport } from './routes/offices/$officeId.search'
import { Route as OfficesOfficeIdMapRouteImport } from './routes/offices/$officeId.map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesIndexRoute = OfficesIndexRouteImport.update({
  id: '/offices/',
  path: '/offices/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRestaurantIdRoute = RestaurantRestaurantIdRouteImport.update({
  id: '/restaurant/$restaurantId',
  path: '/restaurant/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesOfficeIdRoute = OfficesOfficeIdRouteImport.update({
  id: '/offices/$officeId',
  path: '/offices/$officeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesOfficeIdSearchRoute = OfficesOfficeIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => OfficesOfficeIdRoute,
} as any)
const OfficesOfficeIdMapRoute = OfficesOfficeIdMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OfficesOfficeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/offices': typeof OfficesIndexRoute
  '/offices/$officeId/map': typeof OfficesOfficeIdMapRoute
  '/offices/$officeId/search': typeof OfficesOfficeIdSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/offices': typeof OfficesIndexRoute
  '/offices/$officeId/map': typeof OfficesOfficeIdMapRoute
  '/offices/$officeId/search': typeof OfficesOfficeIdSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/offices/$officeId': typeof OfficesOfficeIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/restaurant/$restaurantId': typeof RestaurantRestaurantIdRoute
  '/offices/': typeof OfficesIndexRoute
  '/offices/$officeId/map': typeof OfficesOfficeIdMapRoute
  '/offices/$officeId/search': typeof OfficesOfficeIdSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offices/$officeId'
    | '/profile/$userId'
    | '/restaurant/$restaurantId'
    | '/offices'
    | '/offices/$officeId/map'
    | '/offices/$officeId/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/offices/$officeId'
    | '/profile/$userId'
    | '/restaurant/$restaurantId'
    | '/offices'
    | '/offices/$officeId/map'
    | '/offices/$officeId/search'
  id:
    | '__root__'
    | '/'
    | '/offices/$officeId'
    | '/profile/$userId'
    | '/restaurant/$restaurantId'
    | '/offices/'
    | '/offices/$officeId/map'
    | '/offices/$officeId/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficesOfficeIdRoute: typeof OfficesOfficeIdRouteWithChildren
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  RestaurantRestaurantIdRoute: typeof RestaurantRestaurantIdRoute
  OfficesIndexRoute: typeof OfficesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/': {
      id: '/offices/'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$restaurantId': {
      id: '/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/restaurant/$restaurantId'
      preLoaderRoute: typeof RestaurantRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$officeId': {
      id: '/offices/$officeId'
      path: '/offices/$officeId'
      fullPath: '/offices/$officeId'
      preLoaderRoute: typeof OfficesOfficeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices/$officeId/search': {
      id: '/offices/$officeId/search'
      path: '/search'
      fullPath: '/offices/$officeId/search'
      preLoaderRoute: typeof OfficesOfficeIdSearchRouteImport
      parentRoute: typeof OfficesOfficeIdRoute
    }
    '/offices/$officeId/map': {
      id: '/offices/$officeId/map'
      path: '/map'
      fullPath: '/offices/$officeId/map'
      preLoaderRoute: typeof OfficesOfficeIdMapRouteImport
      parentRoute: typeof OfficesOfficeIdRoute
    }
  }
}

interface OfficesOfficeIdRouteChildren {
  OfficesOfficeIdMapRoute: typeof OfficesOfficeIdMapRoute
  OfficesOfficeIdSearchRoute: typeof OfficesOfficeIdSearchRoute
}

const OfficesOfficeIdRouteChildren: OfficesOfficeIdRouteChildren = {
  OfficesOfficeIdMapRoute: OfficesOfficeIdMapRoute,
  OfficesOfficeIdSearchRoute: OfficesOfficeIdSearchRoute,
}

const OfficesOfficeIdRouteWithChildren = OfficesOfficeIdRoute._addFileChildren(
  OfficesOfficeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficesOfficeIdRoute: OfficesOfficeIdRouteWithChildren,
  ProfileUserIdRoute: ProfileUserIdRoute,
  RestaurantRestaurantIdRoute: RestaurantRestaurantIdRoute,
  OfficesIndexRoute: OfficesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
